version: "3.9"

services:
  yi-tools:
    image: hewm/yi-tools:latest
    container_name: yi-tools
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    volumes:
      - ./logs:/app/logs
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    networks:
      - yi-tools-network

networks:
  yi-tools-network:
    driver: bridge