[project]
name = "yi-tools"
version = "0.1.0"
description = "A collection of utility tools built with FastAPI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "uvicorn[standard]>=0.27.0",
]
